name: bluu_superadmin
description: "Bluu Superadmin Panel - Flutter Web"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Routing
  go_router: ^14.6.2

  # Networking
  dio: ^5.7.0

  # Storage
  shared_preferences: ^2.3.3

  # DI
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
